# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # 1. 编译 Dongle (接收器) 固件
  # 使用原厂左手定义，但通过软件配置使其成为接收 2 个从机的 Central 主机
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_SPLIT_BLE_MAX_PERIPHERALS=2

  # 2. 编译 左手键盘 (从机) 固件
  # 使用原厂左手定义，但通过读取 cradio_left.conf 将其强制降级为从机
  - board: nice_nano_v2
    shield: cradio_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # 3. 编译 右手键盘 固件 (保持原厂默认的从机属性)
  - board: nice_nano_v2
    shield: cradio_right